[tool.poetry]
name = "Flask-recieve"
version = "0.1.0"
description = ""
authors = ["Jorge Escobar <jorge@fromzero.io>"]

[tool.poetry.dependencies]
python = "^3.7"
Flask = "2.0.2"
python-dotenv = "0.19.2"
flask-mongoengine = "1.0.0"
pytest = "6.2.1"
requests = "2.28.1"
SQLAlchemy = "1.4.42"
Flask-SQLAlchemy= "3.0.2"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
black = {version = "^21.7b0", allow-prereleases = true}

[tool.black]
line-length = 80

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"